name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install snap
        run: sudo apt install snap -y
        
      - name: Install latest zig build from master branch
        run: sudo snap install zig --classic --edge
        
      - name: Test
        run: zig build test
